version: "3"

x-node: &node-common
  depends_on:
    - bootnode
  networks:
    - scratch

services:
  bootnode:
    build:
      context: .
      dockerfile: ./node.Dockerfile
    container_name: bootnode
    command: |
      --nodekeyhex="011cfce7fec2c2451627c39ebab77f0157fa4c55be46618b3c860efa467bd7c4"
      --networkid=$NETWORK_ID
      --netrestrict="172.16.254.0/24"
      --ipcdisable
    networks:
      - scratch

  signer1:
    <<: *node-common
    build:
      context: .
      dockerfile: ./signer.Dockerfile
      args:
        privatekey: 232a80e75637028e4080c8f4bf3ade2fcca2dc28c8f0a3f33d244bf8620919c4
        password: "tr#sted24"
    container_name: signer1
    command: |
      --bootnodes="enode://65dd59b0191271e9fd67f2ead01660690498e304d8b3c862df80e9edb3b14fb36784347fb3522f24653a7d34f8888bb9c2509d10f5b27acb7fd5d88d87b19fad@bootnode:30303"
      --syncmode "full"
      --password /.pass
      --unlock 0x42B74898F1E5D638CC3cdDcf908f631752a783Dc
      --mine
      --miner.etherbase 0x42B74898F1E5D638CC3cdDcf908f631752a783Dc
      --networkid=$NETWORK_ID
      --netrestrict="172.16.254.0/24"
      --ipcdisable
    volumes:
      - signer1:/root/.ethereum

  signer2:
    <<: *node-common
    build:
      context: .
      dockerfile: ./signer.Dockerfile
      args:
        privatekey: b1d3b7945a79deb28efe7c30d887f40510feaea261193f9a75ab5325b4fa614f
        password: "tr#sted24"
    container_name: signer2
    command: |
      --bootnodes="enode://65dd59b0191271e9fd67f2ead01660690498e304d8b3c862df80e9edb3b14fb36784347fb3522f24653a7d34f8888bb9c2509d10f5b27acb7fd5d88d87b19fad@bootnode:30303"
      --syncmode "full"
      --password /.pass
      --unlock 0xB0c157df5E1C3CC66A0AF7b5C45Eb0b9480B64Fd
      --mine
      --miner.etherbase 0xB0c157df5E1C3CC66A0AF7b5C45Eb0b9480B64Fd
      --networkid=$NETWORK_ID
      --netrestrict="172.16.254.0/24"
      --ipcdisable
    volumes:
      - signer2:/root/.ethereum

  node1:
    <<: *node-common
    build:
      context: .
      dockerfile: ./node.Dockerfile
    container_name: node1-sync
    command: |
      --bootnodes="enode://65dd59b0191271e9fd67f2ead01660690498e304d8b3c862df80e9edb3b14fb36784347fb3522f24653a7d34f8888bb9c2509d10f5b27acb7fd5d88d87b19fad@bootnode:30303"
      --syncmode "full"
      --networkid=$NETWORK_ID
      --netrestrict="172.16.254.0/24"
      --ipcdisable
    volumes:
      - node1:/root/.ethereum

  node2:
    <<: *node-common
    build:
      context: .
      dockerfile: ./node.Dockerfile
    container_name: node2-rpc
    command: |
      --bootnodes="enode://65dd59b0191271e9fd67f2ead01660690498e304d8b3c862df80e9edb3b14fb36784347fb3522f24653a7d34f8888bb9c2509d10f5b27acb7fd5d88d87b19fad@bootnode:30303"
      --syncmode "full"
      --networkid=$NETWORK_ID
      --netrestrict="172.16.254.0/24"
      --allow-insecure-unlock
      --http
      --http.addr="0.0.0.0"
      --http.api="db,eth,net,web3,personal,web3"
      --http.corsdomain="*"
    ports:
      - 8545:8545
    volumes:
      - node2:/root/.ethereum

volumes:
  signer1:
  signer2:
  node1:
  node2:

networks:
  scratch:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.254.0/24
